plugin:
  name: easydb-detail-map-plugin
  version: 1.0
  server:
    api-version:
      require: 1
  webfrontend:
    url: easydb-detail-map-plugin.js
    css: easydb-detail-map-plugin.css
    l10n: l10n/
    type_extension:
      mask:
        eas:
          - name: map
            parameters:
              show_in_map:
                type: bool
                default: true

base_config:
  - name: detail_map
    group: css
    parameters:
      enabled:
        position: 0
        type: bool
      tiles:
        position: 1
        type: select
        options: ["OpenStreetMaps", "Mapbox"]
        default: "OpenStreetMaps"
      mapboxToken:
        position: 2
        type: text
