plugin:
  name: easydb-detail-map-plugin
  version: 1.0
  server:
    api-version:
      require: 1
  webfrontend:
    url: detail-map.js
    l10n: l10n/

base_config:
  - name: detail_map
    group: css
    parameters:
      enabled:
        name: enabled
        type: bool