plugin:
  name: easydb-detail-map-plugin
  version: 1.0
  server:
    api-version:
      require: 1
  scss:
    body:
      - build/webfrontend/easydb-detail-map-plugin.scss
  webfrontend:
    url: easydb-detail-map-plugin.js
    l10n: l10n/
    type_extension:
      mask:
        eas:
          - name: show_in_map
            parameters:
              type: bool
              default: true

base_config:
  - name: detail_map
    group: css
    parameters:
      enabled:
        position: 0
        type: bool
      tiles:
        position: 1
        type: select
        options: ["OpenStreetMaps", "Mapbox"]
        default: "OpenStreetMaps"
      mapboxToken:
        position: 2
        type: text
